CREATE SCHEMA IF NOT EXISTS main;

CREATE TABLE IF NOT EXISTS main.user (
    id VARCHAR(50) PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS main.session (
    id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50) REFERENCES main.user(id) ON DELETE CASCADE,
    token VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    is_revoked BOOLEAN DEFAULT FALSE,
    revoked_at_ms TIMESTAMP,
    replaced_by_session_id VARCHAR(50) REFERENCES main.session(id)
);